:main_site: https://www.uniyar.ac.ru
:opensource_guide: https://opensource.guide/ru/

= Добро пожаловать в ЯрГУ 👋

Приветствуем тебя в *GitHub@Uniyar*! В link:{main_site}[Ярославском государственном университете им. П.Г. Демидова] мы убеждены, что сочетание открытого мышления и открытой науки позволят нам создавать решения, способные оказать положительное воздействие на общество. В современном мире технологии, данные и программное обеспечение играют решающую роль в этом процессе.

Наш аккаунт на GitHub — это место, где академический и административный персонал университета работают над разработкой и распространением исследовательского кода и программного обеспечения. Мы приглашаем тебя присоединиться к нашим проектам и вместе трудиться над созданием лучшего будущего.

++++
<details>
	<summary>:key: Я работаю в ЯрГУ и хочу получить доступ!</summary>
	<br>
	<ul>
    <p>
     Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </p>
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </p>
    <p>
     Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </p>
	</ul>
</details>

<details>
	<summary>:key: Я учусь в ЯрГУ и хочу использовать GitHub!</summary>
	<br>
	<ul>
    <p>TLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    <p>
     Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    <p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>
	</ul>
</details>
++++

== Как внести вклад

В ЯрГУ мы любим 💛 открытую науку. Это означает, что мы приветствуем участие в наших проектах. Хочешь внести участвовать? Отлично! Нужна помощь? Мы поможем начать работу! Программное обеспечение с открытым исходным кодом создается такими же людьми, как и ты. Узнай больше об этом и том, как link:{opensource_guide}[внести свой вклад].